### ISSUE TITLE
ImageNet (NoSuchEntity) when calling the AttachRolePolicy operation

### ISSUE THREAD

**Issue by verbiiz** [shiftan/simple_sagemaker#30]
When I run the command:

```
ssm shell -p imagenet -t 1-node -o ./output1 --download_state \
  --iis imagenet s3://bucket/imagenet-data \
  --it ml.p3.2xlarge -d main.py -v 280 \
  --cmd_line "CODE_DIR=\`pwd\` && cd \$SSM_INSTANCE_STATE && \
    python \$CODE_DIR/main.py --epochs 10 --resume checkpoint.pth.tar --workers 8 \$SM_CHANNEL_IMAGENET \
    --multiprocessing-distributed --dist-url env:// --world-size \$SSM_NUM_NODES --rank \$SSM_HOST_RANK --seed 123"
```

I get the output error:

```
Traceback (most recent call last):
  File "/usr/local/bin/ssm", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/simple_sagemaker/cli.py", line 997, in main
    args.func(args, hyperparameters)
  File "/usr/local/lib/python3.8/site-packages/simple_sagemaker/cli.py", line 718, in shellHandler
    runHandler(args, hyperparameters)
  File "/usr/local/lib/python3.8/site-packages/simple_sagemaker/cli.py", line 910, in runHandler
    input_data_path, input_distribution, inputs = parseInputsAndAllowAccess(
  File "/usr/local/lib/python3.8/site-packages/simple_sagemaker/cli.py", line 639, in parseInputsAndAllowAccess
    sm_project.allowAccessToS3Bucket(bucket)
  File "/usr/local/lib/python3.8/site-packages/simple_sagemaker/sm_project.py", line 236, in allowAccessToS3Bucket
    iam_utils.allowAccessToS3Bucket(
  File "/usr/local/lib/python3.8/site-packages/simple_sagemaker/iam_utils.py", line 105, in allowAccessToS3Bucket
    response = client.attach_role_policy(
  File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchEntityException: An error occurred (NoSuchEntity) when calling the AttachRolePolicy operation: The role with name SageMakerIAMRole_Imagenet cannot be found.
```

**Comment by verbiiz** [comment]
Now, when I run this command:

```
ssm shell -p imagenet -t 1-node -o ./output1 --download_state \
  --iis imagenet s3://bucket/imagenet-data \
  --it ml.p3.2xlarge -d main.py -v 280 --no_spot \
  --cmd_line "CODE_DIR=\`pwd\` && cd \$SSM_INSTANCE_STATE && \
    python \$CODE_DIR/main.py --epochs 10 --resume checkpoint.pth.tar --workers 8 \$SM_CHANNEL_IMAGENET \
    --multiprocessing-distributed --dist-url env:// --world-size \$SSM_NUM_NODES --rank \$SSM_HOST_RANK --seed 123"
```

It's telling me:

```
Traceback (most recent call last):
  File "/usr/local/bin/ssm", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/simple_sagemaker/cli.py", line 997, in main
    args.func(args, hyperparameters)
  File "/usr/local/lib/python3.8/site-packages/simple_sagemaker/cli.py", line 718, in shellHandler
    runHandler(args, hyperparameters)
  File "/usr/local/lib/python3.8/site-packages/simple_sagemaker/cli.py", line 910, in runHandler
    input_data_path, input_distribution, inputs = parseInputsAndAllowAccess(
  File "/usr/local/lib/python3.8/site-packages/simple_sagemaker/cli.py", line 639, in parseInputsAndAllowAccess
    sm_project.allowAccessToS3Bucket(bucket)
  File "/usr/local/lib/python3.8/site-packages/simple_sagemaker/sm_project.py", line 236, in allowAccessToS3Bucket
    iam_utils.allowAccessToS3Bucket(
  File "/usr/local/lib/python3.8/site-packages/simple_sagemaker/iam_utils.py", line 103, in allowAccessToS3Bucket
    policy_arn = getOrCreatePolicy(client, boto3_session, policy_name, policyString)
  File "/usr/local/lib/python3.8/site-packages/simple_sagemaker/iam_utils.py", line 49, in getOrCreatePolicy
    response = iam_client.create_policy(
  File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.EntityAlreadyExistsException: An error occurred (EntityAlreadyExists) when calling the CreatePolicy operation: A policy called SageMakerIAMRole_imagenet_Policy already exists. Duplicate names are not allowed
```

**Comment by verbiiz** [comment]
For reference, I'm using the following versions:

boto3                         1.15.17
botocore                    1.18.17
simple-sagemaker    0.9.22

**Comment by shiftan** [comment]
Hi Dyllan,

Thanks for reporting that issues.
The first error was fixed in 0.9.23 (to be published in a couple of mins, once testing is done)

About the second one - I couldn't reproduce it, but I believe it's related to a timing issue on AWS, i.e. it takes a few second until a new role is fully "published". If that's correct it should be resolved by running the command again, and should be happening just on the first time a command for a project is launched.
Can you please try to run the command again?

BTW - note that s3://bucket/imagenet-data is a sample path, and should be updated with your own path.

**Comment by verbiiz** [comment]
Thank you, and yes I know the bucket path is a placeholder

**Comment by verbiiz** [comment]
I am still receiving the same error despite having upgraded to version 0.9.23

**Comment by verbiiz** [comment]
I was able to fix it by updating the NAME aspect of this parameter:

`--iis [name] [s3 url]`

to be the s3 url just stripped of the s3:// part.

example:

`--iis imagenet-bucket s3://imagenet-bucket`

not sure why this fixed it, but it did

**Comment by shiftan** [comment]
This is indeed very strange, I can't see the reason for that...
Which of the two errors did you still get?
